apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: aggregator:latest
        imagePullPolicy: Never
        env:
        - name: AMQP_URL
          value: "amqp://rabbitmq-service:5672/%2f"
        - name: RUST_LOG
          value: "info"
