apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-producer
  labels:
    app: iot-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-producer
  template:
    metadata:
      labels:
        app: iot-producer
    spec:
      containers:
      - name: iot-producer
        image: iot-producer:local
        imagePullPolicy: Never
        env:
        - name: AMQP_URL
          value: "amqp://rabbitmq-service:5672/%2f"
        - name: RUST_LOG
          value: "info"
