apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-producer
  labels:
    app: iot-producer
spec:
  replicas: 2 # Scale up or down to mock multiple producers
  selector:
    matchLabels:
      app: iot-producer
  template:
    metadata:
      labels:
        app: iot-producer
    spec:
      containers:
      - name: iot-producer
        image: iot-producer:local # Matches the image you build locally
        imagePullPolicy: Never    # Crucial: Tells K8s to look inside Minikube's local cache
        env:
        - name: AMQP_URL
          value: "amqp://rabbitmq-service:5672/%2f"
        - name: RUST_LOG
          value: "info"
